export const SEND_TYPE_VS_QUANTITY_TICKET = "SEND_TYPE_VS_QUANTITY_TICKET";
export const ADD_SEAT = "ADD_SEAT";
export const REMOVE_SEAT = "REMOVE_SEAT";
export const RESET = "RESET";
export const SEND_BUY_TICKET = "SEND_BUY_TICKET";
